### ISSUE TITLE
Explore and Implement Authentication for Users

### ISSUE THREAD

**Issue by poksyy** [Dynavy/flashfood-project-backend#69]
- Investigate how Laravel handles authentication through the Authenticatable model.

- Research and choose an authentication method (Laravel Sanctum or Passport).
- Configure token-based authentication to allow secure API access.
- Implement endpoints for:
  - User registration.
  - Login to retrieve a token.
  - Logout to revoke tokens.
- Test the authentication flow (token creation, validation, and revocation) using POSTMAN.
- Update the User model if needed (e.g., to include token scopes or related logic).

**Comment by Dynavy** [comment]
All these features have been successfully implemented as of December 30th.

Close #69.
